### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by carlthome** [Peltarion/sidekick#10]
The LICENSE contains both a generic "all rights reserved" line, as well as an excerpt from Apache 2. Which one is in effect?

It's also a bit iffy to me that you list individual licenses for third-party dependencies. What's the reasoning for doing that?

**Comment by johannapeltarion** [comment]
Peltarion owns all rights to Peltarion sidekick. Peltarion sidekick is licensed under the Apache 2.0 License. 

Third-party dependencies are listed because they are required when using sidekick.
