### ISSUE TITLE
Sidekick doesn't support numpy arrays

### ISSUE THREAD

**Issue by agrinh** [Peltarion/sidekick#34]
The platform datatype for numpy arrays is now "numeric", whereas sidekick assumes it's name is "numpy". This makes it impossible to use numpy arrays in Sidekick. See https://github.com/Peltarion/sidekick/blob/6791ceca394a65a7170237c5b7572e88420c9f09/sidekick/encode.py#L212

**Comment by alvaro-garcia-carrasco** [comment]
Fixed here: https://github.com/Peltarion/sidekick/pull/35
